### ISSUE TITLE
Forcing a restart

### ISSUE THREAD

**Issue by mihai-stancu** [amkartashov/restarter#2]
Hi,

Is there a signal that can be sent to `restarter` that can force a restart of the child? The only way I've found to force the restart of the child is to kill the child directly which requires finding its PID or keeping track of it.

INT, QUIT, TERM will be forwarded and the child exits with status 0 so `restarter` also exits with status 0.

Is there any other way to force the restart of the child?

**Comment by amkartashov** [comment]
There is no such functionality atm but I think it'll be easy to add. Just let me know how do you see this.

**Comment by mihai-stancu** [comment]
I was thinking about using:
```bash
kill -s$RESTARTER_RESTART_SIGNAL $RESTARTER_PID;
```

Which should not be counted against the `$RESTARTER_RETRIES`.

Do you have a more elegant solution?

**Comment by amkartashov** [comment]
Yes, we can set and use specific signal to ask restarter to restart application process. Question is: what restarter should do in this case? Send SIGKILL? Send SIGTERM?

**Comment by mihai-stancu** [comment]
It's better to send SIGTERM to give the process a chance to intercept it, cleanup and exit gracefully.

**Comment by amkartashov** [comment]
I have an idea. Restarter exits if child exits with 0. We can just disable this temporarily and then send SIGTERM.

* Add new configuration environment variables RESTARTER_RESTART_SIGNAL (not set by default) and RESTARTER_RESTART_WAIT_SECONDS (30 by default, 0 means forever)
* If restarter got RESTARTER_RESTART_SIGNAL, it waits for a child to finish for RESTARTER_RESTART_WAIT_SECONDS
* During this time, you can send any other signal to restarter (including SIGTERM) and it'll be forwarded to a child as usual. I don't want restarter to do this, because this add flexibility on how we can restart a child - so you can send any signal, or send API request, or pull any other trigger application can react to.
* If child exits during RESTARTER_RESTART_WAIT_SECONDS, even with 0 exit code, restarter will start it again

**Comment by mihai-stancu** [comment]
OK, I'll try to explain the the complete scenario for clarity:

```bash
# at process start time:
export RESTARTER_RESTART_SIGNAL=HUP;
exec -a "restarter-sleeper" restarter sleep infinity;
RESTARTER_SLEEPER_PID=$(pgrep restarter-sleeper);

# at child restart time:
kill -sHUP $RESTARTER_SLEEPER_PID;
# bash pseudocode for internal restarter logic:
disable_exit $RESTARTER_RESTART_WAIT_SECONDS;
kill -sTERM $CHILD_PID;
# the child exits in <= $RESTARTER_RESTART_WAIT_SECONDS
# the child gets restarted
# no increment against $RESTARTER_RETRIES
```

**Comment by mihai-stancu** [comment]
I reread your message and I think I got it wrong.

**Comment by mihai-stancu** [comment]
OK, I'll try to explain the the complete scenario for clarity:

```bash
# at process start time:
export RESTARTER_RESTART_SIGNAL=HUP;
exec -a "restarter-sleeper" restarter sleep infinity;
RESTARTER_SLEEPER_PID=$(pgrep restarter-sleeper);

# at child restart time:
kill -sHUP $RESTARTER_SLEEPER_PID;
kill -sTERM $RESTARTER_SLEEPER_PID;

# bash pseudocode for internal restarter logic:
kill -sTERM $CHILD_PID; # forwarded whatever you sent in the previous line
disable_exit $RESTARTER_RESTART_WAIT_SECONDS;
# the child exits in <= $RESTARTER_RESTART_WAIT_SECONDS
# the child gets restarted
# no increment against $RESTARTER_RETRIES
```

**Comment by mihai-stancu** [comment]
OK so the trigger for activating the greace period of `RESTARTER_RESTART_WAIT_SECONDS` is sending the restart signanl `kill -sHUP $RESTARTER_SLEEPER_PID`.

Note: after the child succesfully restarts this feature should once again be disabled until the next `kill -sHUP`.

**Comment by amkartashov** [comment]
@mihai-stancu ok.

I'll add it soon. Mb this weekend.

**Comment by mihai-stancu** [comment]
Sounds awessome, thank you!

**Comment by amkartashov** [comment]
@mihai-stancu  added into new release, see readme for instructions: https://github.com/amkartashov/restarter?tab=readme-ov-file#force-restart

**Comment by mihai-stancu** [comment]
Thank you, I'll take it for a spin.
